spring.application.name=Boot_Student_Details_Binding_System
student.id=1001
student.name=Nitish Kumer
student.course=Java
student.fee=30000

#dept data
  dept.id[0]=101
  dept.name[0]=HR
  dept.id[1]=102
  dept.name[1]=IT
  dept.id[2]=103
  dept.name[2]=Finance