spring.application.name=Boot_Employee_Configuration_System
employee.id=1001
employee.name=Nitish Kumar
employee.salary=30000
employee.skills[0]=Java
employee.skills[1]=SQL
employee.skill[2]=Spring Boot

employee.project[0]=Employee Management System
employee.project[1]=Vehical Management System

employee.tools[0]= VsCode
employee.tools[1]= Eclips
employee.tools[2]= Git & GitHub

employee.experience.java=4
employee.experience.SQL=3
employee.experience.Spring_Boot=3

add.city=Darbhanga
add.state=bihar
add.pincode=847106

